/*******************************************************************************
Code generated by platkmframework 
*******************************************************************************/


import { useState } from "react";
import { BatchEntriesFormPage } from "./BatchEntriesFormPage";
import { BatchEntriesListPage } from "./BatchEntriesListPage";

export const BatchEntriesListFormPage = () => {

    const [action, setAction] = useState({value:'', id:''});

    return (
        <>
            <BatchEntriesFormPage action={action}  setAction={setAction}/>
            <BatchEntriesListPage action={action}  setAction={setAction}/>
        </>
    )
}