/*******************************************************************************
Code generated by platkmframework 
*******************************************************************************/


import React, { useState, useEffect } from "react";

import { useFetch } from "../../components/hooks/useFetch";
import { useForm } from "../../components/hooks/useForm";
import { useMessage } from "../../components/hooks/useMessage";
import { Message } from "../../components/message/Message";
import { converToLabel } from "../../js/util";


export const ProductsFormPage = ({action, setAction})  => {
  const {formState, setFormState, onInputChange, onResetForm} = useForm({"productId": "","name": "","description": "","categoryId": "","purchasePrice": "","salePrice": "","unit": "","minQuantity": "","batchManaged": "","perishable": "","updatedDate": ""})	
  const {post, put, get} = useFetch();
  const  {clean, error, success, msg} = useMessage();

  const [listCategories, setListCategories] = useState([])

    useEffect(()=>{
		if(action.value == 'cleanForm'){
			if(action.id != undefined && action.id != null  && action.id != '' ){
				if(formState.productId  == action.id ){
					onResetForm();
				}
			}else{
				onResetForm();
			}
		}else if(action.value == 'formEdit'){
			load(action.id);
			
		}
		loadCategories();

    }, [action])


	const loadCategories= ()=>{
		get({url:'categories/list'},
			(status, data)=>{ 
				setListCategories(data) 
			}, (status, msg)=>{
			  error(msg)
			} 
		) 
	}


	const load = (id)=>{
		get({url:'products/' + id},
			(status, data)=>{ 
				setFormState(data)
				clean();
			}, (status, msg)=>{
			  error(msg)
			} 
		) 
	}
	
	const handleSumbit = (event)=>{
		event.preventDefault();
		if(formState.productId == '') 
			post({url:'products', data:{"name": formState.name,"description": formState.description,"categoryId": formState.categoryId,"purchasePrice": formState.purchasePrice,"salePrice": formState.salePrice,"unit": formState.unit,"minQuantity": formState.minQuantity,"batchManaged": formState.batchManaged,"perishable": formState.perishable,"updatedDate": formState.updatedDate}},
				(status, data)=>{ 
					success('Record created') 
					setFormState({...formState, categoryId:data.value})
					setAction({...action, value:'search'})
				}, (status, msg)=>{
					error(msg)
				} 
			) 
		else 
			put({url:'products', data:{"productId": formState.productId,"name": formState.name,"description": formState.description,"categoryId": formState.categoryId,"purchasePrice": formState.purchasePrice,"salePrice": formState.salePrice,"unit": formState.unit,"minQuantity": formState.minQuantity,"batchManaged": formState.batchManaged,"perishable": formState.perishable,"updatedDate": formState.updatedDate}},
				(status, data)=>{ 
					success('Record updated') 
					setAction({...action, value:'search'})
				}, (status, msg)=>{
					error(msg)
				} 
			)  
	}


  return (
    <div className="container">
      <div className="card">
        <div><Message msg={msg}/></div> 
        <h2 className="card-title">
          {formState.productId != '' ? "Edit Products" : "Create Products"}
        </h2> 
<form onSubmit={(event) => handleSumbit(event)}>
            <div className="row">
            <div className="col-md-6 mb-3">
              <label className="form-label">{converToLabel('name')}*</label>
              <input type="text" 
		id="name"
		name="name"
		className="form-control" 
		placeholder="value for name" 
                        maxLength="255"
                         value={formState.name}  
	        onChange={(event)=>{onInputChange(event, 'name')}}
required  />
               
</div>
            <div className="col-md-6 mb-3">
              <label className="form-label">{converToLabel('description')}</label>
              <input type="text" 
		id="description"
		name="description"
		className="form-control" 
		placeholder="value for description" 
                        maxLength="2147483647"
                         value={formState.description}  
	        onChange={(event)=>{onInputChange(event, 'description')}}
  />
               
</div>
            <div className="col-md-6 mb-3">
              <label className="form-label">{converToLabel('categories')}</label>
	<select id="categoryId"
		name="categoryId"
                                    value={formState.categoryId}  
		onChange={(event)=>{onInputChange(event, 'categoryId')}}
>

	{

		listCategories.map((elem,i)=>(
			<option key={'Categories_' + i}>{elem.name}</option>
		))
	}

	</select>
</div>
            <div className="col-md-6 mb-3">
              <label className="form-label">{converToLabel('purchase_price')}*</label>
	<input type="number" id="purchasePrice" className="form-control"
	     name="purchasePrice"   
                       value={formState.purchasePrice}  
                       onChange={(event)=>{onInputChange(event, 'purchasePrice')}}
required />
</div>
            <div className="col-md-6 mb-3">
              <label className="form-label">{converToLabel('sale_price')}*</label>
	<input type="number" id="salePrice" className="form-control"
	     name="salePrice"   
                       value={formState.salePrice}  
                       onChange={(event)=>{onInputChange(event, 'salePrice')}}
required />
</div>
            <div className="col-md-6 mb-3">
              <label className="form-label">{converToLabel('unit')}*</label>
              <input type="text" 
		id="unit"
		name="unit"
		className="form-control" 
		placeholder="value for unit" 
                        maxLength="255"
                         value={formState.unit}  
	        onChange={(event)=>{onInputChange(event, 'unit')}}
required  />
               
</div>
            <div className="col-md-6 mb-3">
              <label className="form-label">{converToLabel('min_quantity')}</label>
	<input type="number" id="minQuantity" className="form-control"
	     name="minQuantity"   
                       value={formState.minQuantity}  
                       onChange={(event)=>{onInputChange(event, 'minQuantity')}}
 />
</div>
            <div className="col-md-6 mb-3">
              <label className="form-label">{converToLabel('batch_managed')}</label>
	<input type="checkbox" id="batchManaged" className="form-check-input"
	     name="batchManaged" />
</div>
            <div className="col-md-6 mb-3">
              <label className="form-label">{converToLabel('perishable')}</label>
	<input type="checkbox" id="perishable" className="form-check-input"
	     name="perishable" />
</div>
            <div className="col-md-6 mb-3">
              <label className="form-label">{converToLabel('updated_date')}</label>
              <input type="date" 
		id="updatedDate"
		name="updatedDate"
		className="form-control" 
		placeholder="value for updatedDate" 
                        maxLength="13"
                         value={formState.updatedDate}  
	        onChange={(event)=>{onInputChange(event, 'updatedDate')}}
  />
</div>
	</div> 
	<div style={{ marginTop: "1rem" }}>
		<button type="submit" className="btn btn-accent">
              		{formState.productId!= '' ? "Update" : "Create"}
            		</button>&nbsp;
		<button type="button" className="btn" onClick={onResetForm}>Clean</button>
	</div>
        </form>
     </div>
   </div>
  );
};
 
