/*******************************************************************************
Code generated by platkmframework 
*******************************************************************************/


import { useState } from "react";
import { ProductsFormPage } from "./ProductsFormPage";
import { ProductsListPage } from "./ProductsListPage";

export const ProductsListFormPage = () => {

    const [action, setAction] = useState({value:'', id:''});

    return (
        <>
            <ProductsFormPage action={action}  setAction={setAction}/>
            <ProductsListPage action={action}  setAction={setAction}/>
        </>
    )
}