/*******************************************************************************
Code generated by platkmframework 
*******************************************************************************/


import { useState } from "react";
import { CategoriesFormPage } from "./CategoriesFormPage";
import { CategoriesListPage } from "./CategoriesListPage";

export const CategoriesListFormPage = () => {

    const [action, setAction] = useState({value:'', id:''});

    return (
        <>
            <CategoriesFormPage action={action}  setAction={setAction}/>
            <CategoriesListPage action={action}  setAction={setAction}/>
        </>
    )
}