/*******************************************************************************
Code generated by platkmframework 
*******************************************************************************/


import React, { useState, useEffect } from "react";

import { useFetch } from "../../components/hooks/useFetch";
import { useForm } from "../../components/hooks/useForm";
import { useMessage } from "../../components/hooks/useMessage";
import { Message } from "../../components/message/Message";
import { converToLabel } from "../../js/util";


export const CategoriesFormPage = ({action, setAction})  => {
  const {formState, setFormState, onInputChange, onResetForm} = useForm({"categoryId": "","name": "","description": ""})	
  const {post, put, get} = useFetch();
  const  {clean, error, success, msg} = useMessage();


    useEffect(()=>{
		if(action.value == 'cleanForm'){
			if(action.id != undefined && action.id != null  && action.id != '' ){
				if(formState.categoryId  == action.id ){
					onResetForm();
				}
			}else{
				onResetForm();
			}
		}else if(action.value == 'formEdit'){
			load(action.id);
			
		}

    }, [action])


	const load = (id)=>{
		get({url:'categories/' + id},
			(status, data)=>{ 
				setFormState(data)
				clean();
			}, (status, msg)=>{
			  error(msg)
			} 
		) 
	}
	
	const handleSumbit = (event)=>{
		event.preventDefault();
		if(formState.categoryId == '') 
			post({url:'categories', data:{"name": formState.name,"description": formState.description}},
				(status, data)=>{ 
					success('Record created') 
					setFormState({...formState, categoryId:data.value})
					setAction({...action, value:'search'})
				}, (status, msg)=>{
					error(msg)
				} 
			) 
		else 
			put({url:'categories', data:{"categoryId": formState.categoryId,"name": formState.name,"description": formState.description}},
				(status, data)=>{ 
					success('Record updated') 
					setAction({...action, value:'search'})
				}, (status, msg)=>{
					error(msg)
				} 
			)  
	}


  return (
    <div className="container">
      <div className="card">
        <div><Message msg={msg}/></div> 
        <h2 className="card-title">
          {formState.categoryId != '' ? "Edit Categories" : "Create Categories"}
        </h2> 
<form onSubmit={(event) => handleSumbit(event)}>
            <div className="row">
            <div className="col-md-6 mb-3">
              <label className="form-label">{converToLabel('name')}*</label>
              <input type="text" 
		id="name"
		name="name"
		className="form-control" 
		placeholder="value for name" 
                        maxLength="255"
                         value={formState.name}  
	        onChange={(event)=>{onInputChange(event, 'name')}}
required  />
               
</div>
            <div className="col-md-6 mb-3">
              <label className="form-label">{converToLabel('description')}</label>
              <input type="text" 
		id="description"
		name="description"
		className="form-control" 
		placeholder="value for description" 
                        maxLength="2147483647"
                         value={formState.description}  
	        onChange={(event)=>{onInputChange(event, 'description')}}
  />
               
</div>
	</div> 
	<div style={{ marginTop: "1rem" }}>
		<button type="submit" className="btn btn-accent">
              		{formState.categoryId!= '' ? "Update" : "Create"}
            		</button>&nbsp;
		<button type="button" className="btn" onClick={onResetForm}>Clean</button>
	</div>
        </form>
     </div>
   </div>
  );
};
 
