/*******************************************************************************
Code generated by platkmframework 
*******************************************************************************/


import { useState } from "react";

import { PopupDialog } from "../../components/dialog/PopupDialog";

import { ClientsFormPage } from "./ClientsFormPage";
import { ClientsListPage } from "./ClientsListPage";

export const ClientsListFormPage = () => {

    const [action, setAction] = useState({value:'', id:''});
    const [open, setOpen] = useState(false);

    return (
        <>
	<PopupDialog open={open} setOpen={setOpen} maxWidth= {'md'} title={'Clients'}>
                	<ClientsFormPage action={action}  setAction={setAction}  />
            	</PopupDialog>
            <ClientsListPage action={action}  setAction={setAction} open={open} setOpen={setOpen}/>
        </>
    )
}